import Head from 'next/head'
import ReceptionBox from '../components/receptionbox'

export default function Home() {
  return (
    <div style={{height:"100%"}}>
      <Head>
        <title>ETALK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReceptionBox/>
    </div>
  )
}
